import type { StyleAudit } from "@/lib/types";

/** Hardcoded mock audit for development and demo purposes */
export const MOCK_AUDIT: StyleAudit = {
  summary:
    "Strong minimalist foundation with clean proportions. The neutral palette works well, but the outfit could use a stronger focal point and more intentional layering to elevate from casual to considered.",
  score: 7.2,
  aesthetic_read: "Quiet Luxury / Minimalist Casual",
  what_works: [
    "Clean color palette — neutrals are well-coordinated without feeling flat",
    "Fit on the trousers is excellent — tapered without being too slim",
    "Shoe choice grounds the outfit with a solid visual anchor",
  ],
  what_to_fix: [
    "Top half lacks structure — the t-shirt reads too casual for the quality of the pants",
    "No accessories — a watch or minimal bracelet would add dimension",
    "Missing a layer — an unstructured blazer or overshirt would complete the silhouette",
  ],
  missing_pieces: [
    "Lightweight unstructured blazer in navy or charcoal",
    "Minimal leather watch with a clean dial",
    "Textured knit polo as a t-shirt upgrade",
  ],
  recommended_categories: [
    "outerwear",
    "accessories",
    "tops",
  ],
  shopping_queries: [
    "unstructured linen blazer men",
    "minimal leather watch under 200",
    "textured knit polo neutral",
  ],
  style_actions: [
    {
      id: "action-1",
      target_item: "neutral palette",
      target_category: "non_shoppable",
      visibility: "visible",
      action: "keep",
      reason: "The neutral palette is coordinated without feeling flat.",
      shoppable: false,
    },
    {
      id: "action-2",
      target_item: "missing structured layer",
      target_category: "outerwear",
      visibility: "missing",
      action: "add",
      reason: "A lightweight blazer or overshirt would complete the silhouette.",
      shoppable: true,
      shopping_intent_id: "intent-1",
    },
    {
      id: "action-3",
      target_item: "missing wrist accessory",
      target_category: "accessories",
      visibility: "missing",
      action: "add",
      reason: "A minimal watch adds dimension without disrupting the restraint.",
      shoppable: true,
      shopping_intent_id: "intent-2",
    },
    {
      id: "action-4",
      target_item: "casual t-shirt",
      target_category: "tops",
      visibility: "visible",
      action: "replace",
      reason: "A textured knit polo would upgrade the top while keeping the palette restrained.",
      shoppable: true,
      shopping_intent_id: "intent-3",
    },
  ],
  shopping_intents: [
    {
      id: "intent-1",
      style_action_id: "action-2",
      category: "outerwear",
      product_type: "blazer",
      style_profile: {
        fit: "relaxed",
        color: "navy",
        material: "linen",
        structure: "unstructured",
        weight: "lightweight",
      },
      display_label: "Lightweight unstructured blazer",
      search_query: "men's unstructured linen blazer navy charcoal",
      alternate_queries: ["men's relaxed linen blazer charcoal"],
      reason: "Adds structure without making the outfit feel formal.",
      priority: 1,
      required_terms: ["blazer"],
      optional_terms: ["linen", "unstructured", "navy", "charcoal"],
      avoid_terms: ["article", "blog", "guide", "pattern", "sewing"],
      replaces_visible_item: false,
    },
    {
      id: "intent-2",
      style_action_id: "action-3",
      category: "accessories",
      product_type: "watch",
      style_profile: {
        material: "leather",
        finish: "minimal",
        placement: "wrist",
      },
      display_label: "Minimal leather watch",
      search_query: "men's minimal leather watch clean dial under 200",
      alternate_queries: ["men's simple leather strap watch white dial"],
      reason: "Adds a quiet accessory detail to the neutral look.",
      priority: 2,
      required_terms: ["watch"],
      optional_terms: ["leather", "minimal", "clean dial"],
      avoid_terms: ["article", "blog", "guide"],
      replaces_visible_item: false,
    },
    {
      id: "intent-3",
      style_action_id: "action-4",
      category: "tops",
      product_type: "knit polo",
      style_profile: {
        fit: "regular",
        color: "cream",
        material: "knit",
        texture: "textured",
        neckline: "collared",
      },
      display_label: "Textured knit polo",
      search_query: "men's textured knit polo neutral",
      alternate_queries: ["men's neutral short sleeve knit polo"],
      reason: "Upgrades the casual top while keeping the palette restrained.",
      priority: 3,
      required_terms: ["polo"],
      optional_terms: ["knit", "textured", "neutral"],
      avoid_terms: ["article", "blog", "guide"],
      replaces_visible_item: true,
    },
  ],
  tone: "direct",
};
